version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - errcheck
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gosec
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
